name: continous_integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: formatting
        uses: psf/black@stable

      - name: ruff
        uses: chartboost/ruff-action@v1

          
      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
          
      # - name: execute py script # run main.py
      #   env:
      #     SOME_SECRET: ${{ secrets.SOME_SECRET }}
      #   run: python main.py
          
      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
