name: continous_integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: ruff
        uses: chartboost/ruff-action@v1
